# serverless.yml
  
service: bms-api-dev

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128
  timeout: 30
  stage: dev
  region: us-east-1
      
        
functions:
  postAuth:
    handler: index.handler
    events:
      - http: 'POST /login'
      - cors: true

plugins:
  - serverless-offline
